/** SAMPLE USER **/
INSERT INTO USER (ID, NAME, SURNAME, USERNAME, PASSWORD, EMAIL, PHONE, REGISTRATION_DATE, ACTIVATED) VALUES (1, 'TestUser', 'TestSurname', 'testuser', '123456', 'testuser@domain.com', '00902124780371', '2016-09-20 09:11:41', true);
INSERT INTO USER_ROLE (ID, ROLE, USER_ID) VALUES (1, 'ROLE_USER', 1);

/** COUNTRY CODES **/
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('AL','Albania','355');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('AR','Argentina','54');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('AU','Australia','61');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('AT','Austria','43');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('BH','Bahrain','973');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('BY','Belarus','375');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('CL','Chile','56');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('CZ','Czech Republic','420');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('DZ','Algeria','213');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('AD','Andorra','376');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('AO','Angola','244');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('AM','Armenia','374');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('AZ','Azerbaijan','994');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('BE','Belgium','32');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('BZ','Belize','501');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('BA','Bosnia and Herzegovina','387');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('BR','Brazil','55');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('BG','Bulgaria','359');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('CM','Cameroon','237');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('CA','Canada','1');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('CN','China,Peoples Republic','86');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('CO','Colombia','57');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('CR','Costa Rica','506');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('CI','Cote d''Ivoire','225');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('HR','Croatia','385');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('CU','Cuba','53');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('CY','Cyprus','357');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('DK','Denmark','45');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('DO','Dominican Republic','1');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('EC','Ecuador','593');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('EG','Egypt','20');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('EE','Estonia','372');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('FI','Finland','358');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('FR','France','33');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('GE','Georgia','995');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('DE','Germany','49');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('GI','Gibraltar','350');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('GR','Greece','30');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('HK','Hong Kong','852');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('HU','Hungary','36');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('IS','Iceland','354');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('IN','India','91');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('ID','Indonesia','62');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('IR','Iran,Islamic Republic of','98');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('IQ','Iraq','964');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('IE','Ireland,Republic of','353');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('IL','Israel','972');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('IT','Italy','39');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('JM','Jamaica','1');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('JP','Japan','81');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('JO','Jordan','962');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('KZ','Kazakhstan','7');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('KE','Kenya','254');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('KP','Korea,Peoples Republic of (North Korea)','850');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('KR','Korea,Republic of (South Korea)','82');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('KW','Kuwait ','965');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('KG','Kyrgyzstan','996');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('LV','Latvia','371');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('LB','Lebanon','961');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('LY','Libya','218');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('LI','Liechtenstein','423');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('LT','Lithuania','370');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('LU','Luxembourg','352');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('MK','Macedonia,Republic of','389');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('MY','Malaysia','60');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('MT','Malta','356');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('MX','Mexico','52');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('MD','Moldova','373');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('MC','Monaco','377');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('MN','Mongolia','976');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('ME','Montenegro','382');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('MA','Morocco','212');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('NL','Netherlands','31');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('NZ','New Zealand','64');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('NI','Nicaragua','505');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('NG','Nigeria','234');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('NO','Norway','47');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('OM','Oman','968');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('PK','Pakistan','92');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('PS','Palestine','970');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('PA','Panama','507');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('PY','Paraguay','595');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('PE','Peru','51');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('PH','Philippines','63');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('PL','Poland','48');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('PT','Portugal','351');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('PR','Puerto Rico','1');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('QA','Qatar','974');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('RO','Romania','40');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('RU','Russian Federation,The','7');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('RS','Serbia','381');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('SG','Singapore','65');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('SK','Slovakia','421');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('SI','Slovenia','386');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('ZA','South Africa','27');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('ES','Spain','34');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('SR','Suriname','597');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('SE','Sweden','46');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('CH','Switzerland','41');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('SY','Syria','963');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('TW','Taiwan','886');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('TJ','Tajikistan','992');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('TH','Thailand','66');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('TT','Trinidad and Tobago','1');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('TN','Tunisia','216');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('TM','Turkmenistan','993');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('UA','Ukraine','380');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('AE','United Arab Emirates','971');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('GB','United Kingdom','44');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('UY','Uruguay','598');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('US','USA','1');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('UZ','Uzbekistan','998');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('VE','Venezuela','58');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('VN','Vietnam','84');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('YE','Yemen','967');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('ZM','Zambia','260');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('ZW','Zimbabwe','263');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('SA','Saudi Arabia','966');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('TR','Turkey','90');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('VU','Vanuatu','678');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('VI','Virgin Islands (U.S.)','1');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('VG','Virgin Islands (British)','1');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('DM','Dominica','1');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('VC','Saint Vincent and the Grenadines','1');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('VA','Holy See (Vatican City State)','379');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('DJ','Djibouti','253');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('UM','United States Minor Outlying Islands','1');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('UG','Uganda','256');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('ET','Ethiopia','251');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('ER','Eritrea','291');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('EH','Western Sahara','212');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('TZ','Tanzania (United Republic of)','255');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('TV','Tuvalu','688');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('GD','Grenada','1');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('GF','French Guiana','33');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('GA','Gabon','241');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('FO','Faroe Islands','298');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('FK','Falkland Islands (Malvinas)','500');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('FJ','Fiji','679');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('FM','Micronesia (Federated States of)','691');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('WS','Samoa','685');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('GY','Guyana','592');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('GW','Guinea-Bissau','245');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('GU','Guam','1');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('GT','Guatemala','502');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('GS','South Georgia and the South Sandwich Islands','500');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('GQ','Equatorial Guinea','240');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('WF','Wallis and Futuna','681');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('GP','Guadeloupe','33');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('GN','Guinea','224');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('GM','Gambia','220');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('GL','Greenland','299');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('GH','Ghana','233');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('GG','Guernsey','44');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('RE','Réunion','262');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('AS','American Samoa','1');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('AQ','Antarctica','672');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('AX','Åland Islands','358');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('AW','Aruba','297');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('PW','Palau','680');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('AG','Antigua and Barbuda','1');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('AF','Afghanistan','93');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('AI','Anguilla','1');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('AN','Netherlands Antilles','599');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('TG','Togo','228');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('BW','Botswana','267');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('TF','French Southern Territories','33');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('BV','Bouvet Island','47');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('TD','Chad','235');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('TK','Tokelau','690');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('BS','Bahamas','1');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('BT','Bhutan','975');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('TO','Tonga','676');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('TL','Timor-Leste','670');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('BF','Burkina Faso','226');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('SV','El Salvador','503');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('BI','Burundi','257');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('ST','Sao Tome and Principe','239');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('BB','Barbados','1');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('SZ','Swaziland','268');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('BD','Bangladesh','880');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('BN','Brunei Darussalam','673');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('BO','Bolivia','591');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('BJ','Benin','229');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('TC','Turks and Caicos Islands','1');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('BM','Bermuda','1');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('SD','Sudan','249');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('SC','Seychelles','248');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('CX','Christmas Island','61');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('CV','Cape Verde','238');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('YT','Mayotte','262');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('SH','Saint Helena','290');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('SJ','Svalbard and Jan Mayen','47');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('SL','Sierra Leone','232');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('SN','Senegal','221');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('SM','San Marino','378');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('SO','Somalia','252');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('CG','Congo','242');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('CF','Central African Republic','236');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('RW','Rwanda','250');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('CC','Cocos (Keeling) Islands','61');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('CD','Congo (The Democratic Republic of)','243');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('CK','Cook Islands','682');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('SB','Solomon Islands','677');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('LS','Lesotho','266');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('LR','Liberia','231');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('MG','Madagascar','261');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('MH','Marshall Islands','692');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('ML','Mali','223');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('MV','Maldives','960');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('MU','Mauritius','230');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('MW','Malawi','265');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('MZ','Mozambique','258');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('MM','Myanmar','95');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('MP','Northern Mariana Islands','1');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('MO','Macao','853');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('MR','Mauritania','222');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('MQ','Martinique','33');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('MS','Montserrat','1');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('NF','Norfolk Island','672');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('NA','Namibia','264');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('NC','New Caledonia','687');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('NE','Niger','227');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('NU','Niue','683');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('NR','Nauru','674');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('NP','Nepal','977');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('PM','Saint Pierre and Miquelon','508');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('PN','Pitcairn','64');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('PF','French Polynesia','689');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('PG','Papua New Guinea','675');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('HN','Honduras','504');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('HM','Heard Island and McDonald Islands','672');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('HT','Haiti','509');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('IM','Isle of Man','44');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('IO','British Indian Ocean Territory','246');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('JE','Jersey','44');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('KI','Kiribati','686');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('KH','Cambodia','855');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('KM','Comoros','269');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('KN','Saint Kitts and Nevis','1');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('KY','Cayman Islands','1');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('LA','Lao Peoples Democratic Republic','856');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('LC','Saint Lucia','1');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('LK','Sri Lanka','94');
INSERT INTO COUNTRY (iso_Code, name, int_phone_code) VALUES ('XK','Kosovo','383');